Kitware/MetaIO

itkThirdParty.h.in
itk_zlib.h
src/metaCommand.cxx
src/metaDTITube.cxx
src/metaLandmark.cxx
src/metaMesh.cxx
src/metaOutput.cxx
src/metaOutput.h

Fixes various warnings

---

src/metaBlob.cxx
src/metaCommand.cxx
src/metaContour.h
src/metaEvent.h
src/metaImageUtils.cxx
src/metaLandmark.cxx
src/metaMesh.h
src/metaOutput.cxx
src/metaOutput.h
src/metaTubeGraph.h
src/metaUtils.cxx

The C++ files now build cleanly with:
-Weverything -Wno-padded -Wno-old-style-cast -Wno-weak-vtables -Wno-c++11-long-long -Wno-c++98-compat-pedantic -Wno-exit-time-destructors -Wno-global-constructors -Wno-float-equal -Wno-conversion -Wno-sign-conversion -Wundefined-bool-conversion -Wstring-conversion -Wno-covered-switch-default -Wno-format-nonliteral

Fixed a bunch of minor warnings from clang

---

src/metaGaussian.cxx

After the recent cahnge to include the Sigma parameter the Radius
parameter failed to be included in the fields for writing.

BUG: The Radius parameter was not being pushed

---

src/metaObject.h

This fix is in reference to VTK bug report 0015529.

metaObject.h: avoid using a single underscore followed by a capital letter

---

CMakeLists.txt
itkMetaIOConfig.h
src/metaArray.cxx
src/metaCommand.cxx
src/metaContour.cxx
src/metaDTITube.cxx
src/metaEllipse.cxx
src/metaForm.cxx
src/metaGaussian.cxx
src/metaGroup.cxx
src/metaImageUtils.cxx
src/metaLandmark.cxx
src/metaLine.cxx
src/metaObject.cxx
src/metaScene.cxx
src/metaSurface.cxx
src/metaTransform.cxx
src/metaTube.cxx
src/metaTubeGraph.cxx
src/metaUtils.cxx
src/metaVesselTube.cxx

---
@bradking @thewtex Another warning VTK might warn about. Manually done with `vim src/*(.)`.

whitespace: remove extra newlines at the end of files

---

src/metaBlob.cxx
src/metaBlob.h

- Changed the data-type of 'm_NPoints' from 'int' to 'size_t' to avoid the
ITK warning message of "Warning C4267 conversion from 'size_t' to 'int'
on VS14.
- Also, the argument data-type of "void NPoints(int npnt)" was changed to
"void NPoint(size_t npt)" to remove the above warning message.
- The return value type of "int NPoints(void)" was replaced with "size_t
NPoints(void).

COMP: Fixed the warning messages of ITK on VS14.

---

src/metaTypes.h

MET_LONG_TYPE was defined as 'int' but MET_ULONG_TYPE is defined
as 'unsigned long'. The two types should be consistent and be
defined based on the same type of variable.

BUG: Inconsistency between MET_LONG_TYPE and MET_ULONG_TYPE

---

.travis.yml
appveyor.yml
src/metaTypes.h
src/metaUtils.cxx
src/metaUtils.h
test/ci/.gitattributes
test/ci/CacheAndUpdateITK.sh
test/ci/appveyor_dashboard.cmake
test/ci/common_dashboard.cmake
test/ci/travis_dashboard.cmake

MetaIO already expects types to have a certain size [1]. (u)int and
(u)long are expected to be encoded on 4 bytes, (u)long long types
are expected to be encoded on 8 bytes. To avoid confusion due to
platform differences, we replace these types that are not visible
or used by the user by fixed width integer types, repectively
(u)int32_t for (u)int and (u)long and (u)unt64_t for (u)long long.
These types are defined in stdint.h
[1] https://github.com/Kitware/MetaIO/blob/master/src/metaTypes.h#L97

ENH: Use integer types with fixed width

---

src/metaUtils.cxx
src/tests/testMeta1Utils.cxx

When adding a suffix to a file name in the MetaIO, the function
MET_SetFileSuffix is used. It checks if the file name already has
an extension, and in that case removes the extension. If it has an
extension, and the new extension starts with '.', it makes sure to
keep only one of the two '.'.
However, if the file name has no extension, and there no was check
to verify that the given extension started with '.'. This lead to
create file names without a '.' and with the file name concatenated
with the extension with no separator. This patch fixes this issue.

BUG: Missing one case in MET_SetFileSuffix

---

src/metaObject.cxx
src/metaObject.h

The static local variable can be shared between threads and may pose
an issue with concurrent access or initialization. The storage has
been made a mutable member variable to preserve the const accessors of
AnatomicalOrientationAcronym and yet still allow multiple instances of
metaObject to be used concurrently.

BUG: Remove static global c string used for storage of orientation

---

.circleci/config.yml
.travis.yml
test/ci/Dockerfile
test/ci/build.sh
test/ci/run.sh
test/ci/test.sh

Create a Docker image with the testing environment. This image can be built by
calling test/ci/build.sh. To test merging this repository into ITK,
re-building ITK, and running ITK's MetaIO tests, call test/ci/run.sh.

ENH: Run ITK tests on CircleCI

---

INSTALL.txt

Numerous updates, links changes, etc. GCC 2.95 is no longer a modern compiler
;-).

DOC: Update INSTALL.txt

---

src/metaObject.cxx
src/metaUtils.cxx

This fixes writing compressed image files > 4GB, as well as reading such files.
There were two major issues:
* The `MET_PerformCompression` function passed an overflow-truncated version of the actual available bytes to deflate; so actually only the first (ActualByteSize % UINT_MAX) bytes were ever pased into zlib. I've rewritten the loop to pass in chunks of (currently up to) 4GB until all available bytes have been processed by deflate; the behavior of the `MET_PerformUncompression` function was very similar.
* In writing the CompressedDataSize, the element was assumed to be of type MET_UINT. This caused the value to be truncated as well to  (ActualByteSize % UINT_MAX). Not sure if my fix of setting the value to MET_ULONG_LONG and fixing the writing of those values is proper, there's two …

Fix (Un)Compression of files (and buffers) > 4GB

---

test/ci/CacheAndUpdateITK.sh

This should address the following error on Appveyor:
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.

BUG: Address fatal error when merging MetaIO changes into ITK in CI

---

src/metaArray.h
src/metaArrow.h
src/metaBlob.h
src/metaContour.h
src/metaDTITube.h
src/metaEllipse.h
src/metaFEMObject.h
src/metaGaussian.h
src/metaGroup.h
src/metaImage.h
src/metaLandmark.h
src/metaLine.h
src/metaMesh.h
src/metaOutput.h
src/metaScene.h
src/metaSurface.h
src/metaTransform.h
src/metaTube.h
src/metaTubeGraph.h
src/metaTypes.h
src/metaVesselTube.h

Though non-C++11 compilers still need to be supported, so use the
keyword through a macro instead.
Fixes #36.

c++11: use `override` where possible

---

src/metaImage.cxx
src/metaImage.h
src/metaObject.cxx
src/metaObject.h

This provide a backward compatible API to update MetaIO without changing any test in ITK while preparing the MetaIO internals to handle spacing as double.

Element spacing as double

---

src/metaObject.cxx

The conversion of a floating-point to text and back is exact as long as
at least `max_digits10` is used (17 for double).
The net effect is that the text representation is now closer to the
DICOM Image Orientation (Patient) or Image Position (Patient) attribute
and will allow easier conversion from one representation to the other.
Since commit InsightSoftwareConsortium/ITK@e532c682930f ITK explicitly set the default precision to 6,
change of default will be transparent.

BUG: Change the default precision for printing double value

---

src/CMakeLists.txt

---
Typo when transcribing into metaio master from VTK.

cmake: fix a typo for VTK's module system

---

test/ci/Dockerfile

This includes an update to the image baseline to account for MetaIO precision
increases in Kitware/MetaIO@62b654327a9ee5590eb3b503e2bb4f0de0904b68
CC: @cquammen @malaterre @jcfr @fbudin69500

ENH: Bump ITK version in CircleCI / Docker build

---

src/metaImage.cxx

Trivial source comment  typos

---

src/metaArray.cxx
src/metaImage.cxx

Example message:
/home/kitware/dashboards/buildbot/vtk_master-eeloo-linux-shared-release_mpi_nogl/source/Utilities/MetaIO/vtkmetaio/metaImage.cxx: In member function 'bool vtkmetaio::MetaImage::M_WriteElements(std::ofstream*, const void*, std::streamoff)':
/home/kitware/dashboards/buildbot/vtk_master-eeloo-linux-shared-release_mpi_nogl/source/Utilities/MetaIO/vtkmetaio/metaImage.cxx:2580:29: warning: '%s' directive writing up to 254 bytes into a region of size between 1 and 2048 [-Wformat-overflow=]
sprintf(dataFileName, "%s%s", pathName, m_ElementDataFileName);
^~~~~~
/home/kitware/dashboards/buildbot/vtk_master-eeloo-linux-shared-release_mpi_nogl/source/Utilities/MetaIO/vtkmetaio/metaImage.cxx:2580:14: note: 'sprintf' output between 1 and 2302 bytes into a destination of size 2048 …

Increasing buffer sizes to avoid warnings coming from usage of sprintf

---

src/metaArray.cxx
src/metaArrow.cxx
src/metaCommand.cxx
src/metaDTITube.cxx
src/metaImage.cxx

- removed a redundant null check
- C to C++ style casts
- remove unnecessary c_str() calls
- return early instead of underflowing an array
- set uninitialized fields of a struct

Fixed some cppcheck warnings

---

appveyor.yml

Visual Studio 2008 does not support C++11.
@seanm @dzenanz @jcfr please take a look.

ENH: Disable VS 2008 and enable VS 2017 CI build

---

src/CMakeLists.txt

To address:
https://github.com/InsightSoftwareConsortium/ITK/issues/619
from regression introduced in:
https://github.com/Kitware/MetaIO/commit/81e134c37dd789000a0cbbed63b65fbdc82013f3

COMP: Add missing headers for installation

---

src/metaArray.cxx
src/metaArray.h
src/metaForm.cxx
src/metaForm.h
src/metaImage.cxx
src/metaImage.h
src/metaImageUtils.cxx
src/metaImageUtils.h
src/metaObject.cxx
src/metaObject.h
src/metaScene.cxx
src/metaUtils.cxx
src/metaUtils.h
src/tests/testMeta1Utils.cxx

Sadly, this alone is not fixing https://github.com/InsightSoftwareConsortium/ITK/issues/852 for me. But it does fix it for original reporter.

Remove length limitation for file names and other maintenance

---

src/tests/testMeta6Surface.cxx

This also has a side-effect of testing the recently updated CI.
Closes #77.

STYLE: trim trailing white-space

---

src/metaArrow.cxx
src/metaBlob.cxx
src/metaContour.cxx
src/metaDTITube.cxx
src/metaEllipse.cxx
src/metaFEMObject.cxx
src/metaGaussian.cxx
src/metaGroup.cxx
src/metaImage.cxx
src/metaLandmark.cxx
src/metaLine.cxx
src/metaMesh.cxx
src/metaScene.cxx
src/metaSurface.cxx
src/metaTransform.cxx
src/metaTube.cxx
src/metaTubeGraph.cxx
src/metaVesselTube.cxx

Previously ObjectTypeName was only set for metaObject (top level) in
the Clear() function and was set in the M_SetupWriteFields() of
derived classes.  Therefore, the value was fixed at "Object" until
the write command was called or a file was read (that then set the
type).
In this fixed version, the ObjectTypeName value is set in the Clear()
function of metaObject and its derived classes (and not in the
M_SetupWriteFields() function).  Therefore, its value is correct
as soon as the class is instantiated.

BUG: ObjectTypeName must be set in Clear() of derived types.

---

src/metaArray.h
src/metaCommand.cxx
src/metaForm.h
src/metaImage.h
src/metaObject.cxx
src/metaObject.h
src/metaOutput.h
src/metaScene.h
src/metaUtils.h
src/tests/testMeta12Array.cxx

Now compiles cleanly with clang -Wzero-as-null-pointer-constant.

Replaced some NULLs and 0s with nullptr

---

src/metaTypes.h

We can do this now that both VTK and ITK require C++11.

COMP: remove pre-VS2015 backwards compatibility definition of snprintf

---

src/metaCommand.cxx
src/metaCommand.h

Added const to function arg.
All MetaIO test pass.

ENH: Parse() should handle char *argv[] as const

---

src/CMakeLists.txt
src/metaObject.cxx
src/metaScene.cxx
src/metaTube.cxx
src/metaTube.h

Extends MetaTubePoint to allow for arbitrary fields to be added to every point.   This allows every point along a tube to have a vector/payload of additional information.
This change required fixing MetaTube to allow arbitrary ordering of information for its points.

Tube point fields

---

src/metaUtils.cxx

MetaIO `MET_Read` did read at most 499 chars from a MET_STRING field,
while `MET_FieldRecordType::value` allows storing up to 32767 chars,
as it is an array of 4096 (`MET_MAX_NUMBER_OF_FIELD_VALUES`) 64-bit
`double` elements. (Only one extra byte is needed for a terminating zero
character.)
This commit allows reading up to 32767 chars into a MET_STRING field.
Note that `MET_Write` already supports writing such large string values.

ENH: MetaIO support reading strings of >= 500 chars (up to 32767 chars)

---

src/metaTube.h

Building CXX object Modules/IO/SpatialObjects/test/CMakeFiles/ITKIOSpatialObjectsTestDriver.dir/itkReadWriteSpatialObjectTest.cxx.o
In file included from ITK/Modules/ThirdParty/MetaIO/src/MetaIO/src/metaScene.h:18:0,
from ITK/Modules/Core/SpatialObjects/include/itkMetaSceneConverter.h:24,
from ITK/Modules/IO/SpatialObjects/include/itkSpatialObjectWriter.h:21,
from ITK/Modules/IO/SpatialObjects/test/itkReadWriteSpatialObjectTest.cxx:19:
ITK/Modules/ThirdParty/MetaIO/src/MetaIO/src/metaObject.h:125:3:
warning: ‘virtual void MetaObject::CopyInfo(const MetaObject*)’ was hidden [-Woverloaded-virtual]
CopyInfo(const MetaObject * _object);
^~~~~~~~

COMP: Fix hidden overloaded-virtual warning

---

src/metaImage.cxx

The m_CompressionTable ivar was detected by valgrind as not being
deleted. In 632a827, the MetaImage::M_Delete was renamed to
M_ResetValues; this is the method which handles resource
deleting.
Closes #100.

BUG: Fix MetaImage::m_CompressionTable leak

---

src/metaObject.cxx
src/metaTube.cxx
src/metaTube.h
src/metaUtils.cxx

Specifically: -Wtautological-unsigned-zero-compare, -Wextra-semi, and -Wsign-compare

Fixed various clang warnings

---

src/metaUtils.h

Fixed the following warning from Visual C++/Visual Studio 2019 (which
occurs when all warnings are enabled, by "/Wall"):
> metaUtils.h(43,13): warning C4619: #pragma warning: there is no warning number '4284'
VS2015, VS2017, and VS2019 no longer produce warning C4284.

COMP: Fix VS2019 /Wall warning: there is no warning number '4284'

---

src/metaObject.cxx

Cast value for CompressedDataSize to its actual type, std::streamoff

Fix >2GB compressed files read problem

---

src/metaImage.cxx

Many calls to private functions (e.g., M_ReadElementsROI) did not check or propagate return values, so errors were not being caught, and ITK reading was failing silently on invalid files.
Also ROI reading of compressed data was not computing size of data being read correctly, so once we started catching errors, the function was reporting requested data size not matching returned
data size and was now failing with checks added.   Fixed the
computation of gc in M_ReadElementsROI for compressed data.
See discussion: https://discourse.itk.org/t/metaimage-m-readelementsroi-data-not-read-completely/4269/9

BUG: Propagate return values from functions to catch errors

---

src/metaImage.cxx
src/metaImage.h
src/metaObject.cxx
src/metaObject.h
src/tests/testMeta3Image.cxx

The MetaObject framework uses multiple keywords. Additionally it allows the user to specify user fields (metadata). When the user fields use the same names as the keywords, writing succeeds but the resulting files are not valid. This commit adds a check so that the user cannot name a user supplied field using a reserved keyword.
resolves #54

BUG: Do not allow user fields with the same names as keywords.

---

CMakeLists.txt
metaIOConfig.h
src/CMakeLists.txt
src/localMetaConfiguration.h
src/metaArray.cxx
src/metaArray.h
src/metaCommand.cxx
src/metaForm.cxx
src/metaForm.h
src/metaImage.cxx
src/metaImage.h
src/metaMesh.h
src/metaObject.cxx
src/metaObject.h
src/metaScene.cxx
src/metaUtils.cxx
src/metaUtils.h

Addresses the following issues:
https://github.com/Kitware/MetaIO/issues/106
https://github.com/Kitware/MetaIO/pull/113
Also, for VTK:
https://gitlab.kitware.com/vtk/vtk/-/merge_requests/6716#note_908828
Of course, VTK seems to have dropped MetaIO support, but most medical imaging apps that use VTK actually use ITK for IO, so these fixes are still relevant to that community.
All ITK tests pass with these changes.
Thoughts?
@todoooo
@codeling 
@hjmjohnson

ENH: Restored use of METAIO_STREAM with ifstream/ofstream

---

src/metaScene.cxx
src/metaUtils.cxx
src/metaUtils.h

This rule was followed when writing all objects, except metaScene.  This commit fixes metaScene.  Additionally, MET_Read/ReadType will look at the first three tag/value pairs in a meta file to determine an object type, so it is more robust, but it will throw warnings regarding unknown fields if the first line isn't ObjectType.

BUG: When writing a MetaIO file, the first line must be ObjectType

---

src/metaUtils.cxx

Reading objectType and objectSubType is done without knowledge of the type, and thereby without knowing what fields will be present or knowing their order of presentation.  Therefore, fields may be encountered that are "unrecognized" when reading the Type / SubType info.  Previously this would produce an "unrecognized field" warning. This commit suppressed those warnings.

ENH: Suppress warnings when reading ObjectType and ObjectSubType

---

src/metaUtils.cxx

GetObjectSubType reading was also reading ObjectType from the file, and that wasn't necessary and produced a memory leak.   This commit fixes those issues.
Also, now the file parsing terminates when ObjectSubType has been read by the GetObjectSubType() function - avoiding parsing of the entire file.

BUG: Memory leak in GetObjectSubType due to unused tag/record

---

src/metaImage.cxx

Modality type name should be like MET_MOD_CT and MET_MOD_MR defined in metaImageTypes.h, not things like MET_SHORT defined in metaTypes.h.

Fix invalid modality type name

---

README.rst

Migrated from the ITK MediaWiki, which is no longer active, to ITK's Markdown documentation.

DOC: Update documentation link
